services:
  fastapi:
    container_name: test-caas-fastapi
    build:
      context: ./app
      dockerfile: fastapi.Dockerfile
    ports:
      - "7002:8000"
    environment:
      - REDIS_HOST=test-caas-redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=test-caas-rabbitmq
      - RABBITMQ_PORT=5672
      - MONGODB_DB=caas
      - MONGODB_HOST=test-caas-mongodb
      - MONGODB_PORT=27017
      - FLOWER_URL=http://test-caas-flower:5555
    depends_on:
      - mongodb
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4-management
    container_name: test-caas-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    tmpfs:
      - /var/lib/rabbitmq
      - /var/log/rabbitmq
    
  clustering:
    container_name: test-caas-clustering_worker
    build:
      context: ./app
      dockerfile: clustering_worker.Dockerfile
    environment:
      - RABBITMQ_HOST=test-caas-rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=test-caas-redis
      - REDIS_PORT=6379
      - FASTAPI_HOST=test-caas-fastapi
      - FASTAPI_PORT=8000
      - FASTAPI_PROTOCOL=http
    depends_on:
      - rabbitmq

  mongodb:
    image: mongo
    container_name: test-caas-mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb/init:/docker-entrypoint-initdb.d
    tmpfs:
      - /data/db

  redis:
    image: redis
    restart: unless-stopped
    container_name: test-caas-redis

  flower:
    container_name: test-caas-flower
    build:
      context: ./app
      dockerfile: clustering_worker.Dockerfile
    command: celery -A "workers.clustering.worker_tasks" flower --port=5555
    environment:
      - RABBITMQ_HOST=test-caas-rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=test-caas-redis
      - REDIS_PORT=6379
      - FASTAPI_HOST=test-caas-fastapi
      - FASTAPI_PORT=8000
      - FASTAPI_PROTOCOL=http
      - FLOWER_UNAUTHENTICATED_API=true
    depends_on:
      - rabbitmq

  automl-worker:
    container_name: test-caas-automl_worker
    build:
      context: ./app
      dockerfile: automl.Dockerfile
    environment:
      - REDIS_HOST=test-caas-redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=test-caas-rabbitmq
      - RABBITMQ_PORT=5672
      - FASTAPI_HOST=test-caas-fastapi
      - FASTAPI_PORT=8000
      - FASTAPI_PROTOCOL=http
    depends_on:
      - redis
    restart: always
