services:
  fastapi:
    container_name: caas-fastapi
    build:
      context: ./app
      dockerfile: fastapi.Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --reload
    ports:
      - "7001:8000"
    volumes:
      - ./app/api/:/app/api # For hot reload
    env_file:
      - ./message_broker/.env
      - ./redis/.env
      - ./mongodb/.env
    environment:
      - DEBUG=1 # For hot reload
      - MINIO_URL=caas-minio:9000
      - MINIO_ACCESS_KEY=minio_admin
      - MINIO_SECRET_KEY=minio_admin
      - MINIO_BUCKET_NAME=caas-data
      - FLOWER_URL=http://caas-flower:5555

  streamlit:
    container_name: caas-streamlit
    build:
      context: ./app
      dockerfile: streamlit.Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ./app/api/.env

  rabbitmq:
    image: rabbitmq:4-management
    container_name: caas-rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./message_broker/.env
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    # - type: bind
    #   source: ./message_broker/.erlang.cookie
    #   target: /var/lib/rabbitmq/.erlang.cookie
    #   read_only: true
    user: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 2s

  clustering:
    container_name: caas-clustering_worker
    build:
      context: ./app
      dockerfile: clustering_worker.Dockerfile
    env_file:
      - ./message_broker/.env
      - ./redis/.env
      - ./app/api/.env
    depends_on:
      rabbitmq:
        condition: service_healthy

  mongodb:
    image: mongo
    container_name: caas-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    env_file:
      - ./mongodb/.env

  minio:
    image: minio/minio
    container_name: caas-minio
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio_admin
      MINIO_SECRET_KEY: minio_admin

  redis:
    image: redis
    restart: unless-stopped
    container_name: caas-redis
    ports:
      - '6379:6379'

  flower:
    container_name: caas-flower
    build:
      context: ./app
      dockerfile: clustering_worker.Dockerfile
    command: celery -A "workers.clustering.worker_tasks" flower --port=5555
    env_file:
      - ./message_broker/.env
      - ./redis/.env
      - ./app/api/.env
    environment:
      - FLOWER_UNAUTHENTICATED_API=true
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

  automl-worker:
    container_name: caas-automl_worker
    build:
      context: ./app
      dockerfile: automl.Dockerfile
    volumes:
      - ./app:/app
    env_file:
      - ./message_broker/.env
      - ./redis/.env
    depends_on:
      - redis
    restart: always

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  mongodb-data:
    driver: local
  minio-data:
    driver: local
