[pytest]
pythonpath = ./app
filterwarnings =
    ignore:PendingDeprecationWarning
    ignore:Please use `import python_multipart` instead.:PendingDeprecationWarning
asyncio_default_fixture_loop_scope = session