services:
  mongodb:
    image: mongo
    container_name: caas-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - caas-net

networks:
  caas-net:
    driver: bridge
    external: true
