auth:
  existingSecret: mongodb-root-password
  username: root
  database: caas
architecture: standalone
persistence:
  storageClass: standard
service:
  type: NodePort
  port: 27017

initdbScripts:
  01-init-mongodb.js: |

    db = db.getSiblingDB('caas');
    db.createCollection('data');
    db.createCollection('results');


