services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: caas-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - caas-net

networks:
  caas-net:
    driver: bridge
    external: true

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local