
\c caas -- connect to the new database

CREATE TABLE IF NOT EXISTS clusterings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_name VARCHAR(50) NOT NULL,
    clustered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    performance_metric_1 DOUBLE PRECISION,
);

