name: Unit Tests AutoML

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout application repository
      uses: actions/checkout@v4

    - name: Run pytest 
      run: pytest app/clustering/tests/