name: Unit Tests AutoML

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout application repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for automl-worker
      uses: docker/build-push-action@v5
      with:
        context: ./app
        file: ./app/automl.Dockerfile
        tags: automl-test:latest
        load: true

    - name: Run pytest in Docker container
      run: |
        docker run --rm automl-test:latest pytest workers/automl/tests/ -v 