name: Unit Tests Clustering

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout application repository
      uses: actions/checkout@v4

    - name: Install packages 
      run: |
        pip install -r app/clustering_worker-requirements.txt
        pip install pytest

    - name: Run pytest 
      run: pytest app/clustering/tests/